### ISSUE TITLE
CSP Query string information not shown in CSP results view

### ISSUE THREAD

**Issue by OrNol** [report-uri/report-uri-bugs#100]
For detailed analysis we want to keep the query string in the URI column in the CSP results view.
To achieve this I disabled the "Remove query string" filter. When running in the free tier on my personal account this worked fine.

I upgraded to a paid tier and added a new corporate team to my personal account.
Reports to the new team end point never show the query string for some reason.
I captured this report request with Fiddler and sent it to the old personal end point. There it does show the query string as expected in the CSP results view so it seems to be some configuration issue or bug.

I can provide the account/end point in private if necessary.

**Comment by ScottHelme** [comment]
Hi @OrNol,

The filter settings on your personal account are not used on the team account, this is probably why you are seeing different behaviour.

To alter the filter settings for your team account, switch to the team and then go to the Filters page and configure the same settings. This should resolve your issue, but let me know if you need further assistance. 

If this does resolve it, please close this bug.

**Comment by OrNol** [comment]
Hi @ScottHelme , thank you for the quick response. I made sure the personal and team settings are setup similarly. I just forgot to mention it above. Hence the surprise the outcome is different in the CSP results view.

**Comment by OrNol** [comment]
Hi @ScottHelme , Any thoughts on this issue? As mentioned above I don't see any reason in the configuration side why the query string is not logged for the team account.

**Comment by spaze** [comment]
Hi @OrNol, and thanks for reporting the issue. I've now found the problem and fixed it. We'll deploy the fix soon and will let you know here once done. Thanks again and sorry for any trouble.

**Comment by OrNol** [comment]
Hi @spaze, great news. Thank you for the confirmation, I'll wait for your update.

**Comment by spaze** [comment]
Hi @OrNol, the fix has now been deployed. Please test and let us know if you have any more issues. Thanks again!

**Comment by OrNol** [comment]
Hi @spaze, I did a quick check and the query string shows the details now as expected. I also tried to disable the "Remove query string" (as this is the preferred value) but the query string kept on showing up. Not sure if there's some kind of delay or logic (I used the same base page for my test) that can explain this behavior?

**Comment by spaze** [comment]
@OrNol thanks for confirming the query string is included after the config change as expected. Currently, there is a small delay, up to 5 minutes, after the config change so you could temporarily see query strings in reports even when you have the "Remove query string" option enabled. It doesn't make much sense and we wanted to remove the delay anyway so I'll prepare a code change and the delay should be gone soon. Thanks again.

**Comment by OrNol** [comment]
@spaze thank you for the feedback. The issue is solved so I closed it.
