### ISSUE TITLE
Activation Email not received

### ISSUE THREAD

**Issue by yvele** [report-uri/report-uri-bugs#101]
I created 2 accounts, for the first one everything went well.
But for the second one, I had some misconfigured Google Mail account, I fixed the problem and then I click the "Send Activation Email" button again.

But I did not receive any mail 🤔 is there any problem you side?

PS: My email works nicely, I tested it many times

**Comment by ScottHelme** [comment]
Hi @yvele,

Could you email directly and I can take a look at this for you?

Cheers, 

Scott
scott@report-uri.com

**Comment by yvele** [comment]
Thanks, I've just sent you an email

**Comment by ScottHelme** [comment]
Got it. Will close this ticket and move the conversation to email.
