### ISSUE TITLE
Where are CSP reports?

### ISSUE THREAD

**Issue by dimaqq** [report-uri/report-uri-bugs#104]
Apologies if I'm just dumb or something... The "home" page shows that I have the reports:

<img width="411" alt="Screenshot 2019-05-29 at 11 42 58" src="https://user-images.githubusercontent.com/662249/58526394-d4527100-8209-11e9-9f49-70430cded3bd.png">

I know these are new, because I'm developing something now and as I test my policy the number is increasing, perhaps with 30 minute delay. Both Chrome and Safari DP show that they send the reports to the `enforce` endpoint.

But when I click `CSP` on that page, or go to CSP section, there's always "no results":

<img width="1697" alt="Screenshot 2019-05-29 at 11 43 17" src="https://user-images.githubusercontent.com/662249/58526472-07950000-820a-11e9-8cdb-5ea52d7071d6.png">

**Comment by ScottHelme** [comment]
Hi @dimaqq, the table show the 24 reports are in the rejected section which means they will not show up in your account. Is your account activated? That's usually the cause of this problem.

**Comment by dimaqq** [comment]
> Hi @dimaqq, the table show the 24 reports are in the rejected section which means they will not show up in your account. Is your account activated? That's usually the cause of this problem.

That must've been it.
I'm positive I've clicked the activation link before when I just registered, but I've clicked it again now, there was no error, and now I have data!
