### ISSUE TITLE
The handling of teams in reports vs graphs is confusing

### ISSUE THREAD

**Issue by stof** [report-uri/report-uri-bugs#106]
When I am on my personal team (in which I collect no data, as everything goes to an actual team), DMARC graphs still take into account the team data, while reports are empty.

This looks similar to my previous report at https://github.com/report-uri/report-uri-bugs/issues/73 (which was for CSP).

**Comment by ScottHelme** [comment]
This sounds odd, will take a look!

**Comment by spaze** [comment]
Hey @stof, you're totally right, and thanks for the report. We've fixed that now, and just like in #73, your old data won't be removed from the graphs but going forward, team data won't "bleed" into your personal account. I also made sure it won't happen again (for example with other report types that might be added in the future) with a bit of refactoring and auto tests. Thanks!

**Comment by stof** [comment]
Thanks a lot (and now looking forward to #52 as I won't have anything in my personal account)

**Comment by spaze** [comment]
Hey @stof, just letting you know that there's some news in #52 which you may like :-) Feel free to close this bug, if the DMARC graphs look fine. Thanks again!
