### ISSUE TITLE
Sorting DMARC reports by number of emails is broken

### ISSUE THREAD

**Issue by stof** [report-uri/report-uri-bugs#107]
I guess this is related to the thousands separator, which breaks the numeric sorting.
![report_uri_dmarc_sort](https://user-images.githubusercontent.com/439401/59495695-2ba24380-8e90-11e9-900b-6203d0dbb30f.png)

Sorting in descending order is even more confusing:
![report_uri_dmarc_sort_desc](https://user-images.githubusercontent.com/439401/59495783-5391a700-8e90-11e9-9def-27578a28f7c3.png)

**Comment by spaze** [comment]
Hey @stof, thanks for the report. You're right, it was the separator added at the wrong time :-) I've fixed it, and it sorts properly now. You can close this if that's the case. Thanks again!

**Comment by stof** [comment]
I confirm that the sorting now works fine. But the separator is now entirely gone. Not sure if this is expected
![report_uri_sorting_bugfix](https://user-images.githubusercontent.com/439401/59775969-51758100-92b2-11e9-92bc-711c07a920e1.png)

**Comment by spaze** [comment]
Oh, my bad 😊 It should be back now. Thanks again!

**Comment by stof** [comment]
I confirm that this is fixed, so closing.
