### ISSUE TITLE
Docs website is broken

### ISSUE THREAD

**Issue by stof** [report-uri/report-uri-bugs#108]
The JS does not load due to CSP (well, I hope the reporting might already have warned you about that, given the nature of the service)

**Comment by ScottHelme** [comment]
Hi @stof, could you give me a little more information? Do you mean the JS doesn't load on your site somewhere?

**Comment by ScottHelme** [comment]
Hey @stof, can you check now and let me know if you still see the same problem?

**Comment by stof** [comment]
This is now working.
