### ISSUE TITLE
Browser extension signature: maddon-pkg

### ISSUE THREAD

**Issue by gwire** [report-uri/report-uri-bugs#11]
The url `mxaddon-pkg` should be suppressed.

```
        "blocked-uri": "mxaddon-pkg",
        "source-file": "mxaddon-pkg",
```

According to this [gist](https://gist.github.com/oreoshake/2c8476f7ecda5fe930b7/) (from [Twitter's CSP handling](https://oreoshake.github.io/csp/twitter/2014/07/25/twitters-csp-report-collector-design.html)) it indicates a plugin for the Maxthon browser.

**Comment by ScottHelme** [comment]
This has been added on the dev site and should hit test and then live soon. 

https://dev.report-uri.io/account/filters/
