### ISSUE TITLE
/ajax/time/ct/ is 500ing

### ISSUE THREAD

**Issue by lol768** [report-uri/report-uri-bugs#110]
POST to `https://report-uri.com/ajax/time/ct/` fails consistently with a 500 Internal Server Error.

This breaks the list on `https://report-uri.com/account/reports/ct/`. Changing the number of records does not help.

There is no response body. Example response happened at date: Wed, 03 Jul 2019 14:20:49 GMT

<details>
<summary>POST data</summary>
<pre>
draw=2
columns[0][data]=0
columns[0][name]
columns[0][searchable]=true
columns[0][orderable]=true
columns[0][search][value]
columns[0][search][regex]=false
columns[1][data]=1
columns[1][name]
columns[1][searchable]=true
columns[1][orderable]=true
columns[1][search][value]
columns[1][search][regex]=false
columns[2][data]=2
columns[2][name]
columns[2][searchable]=true
columns[2][orderable]=true
columns[2][search][value]
columns[2][search][regex]=false
columns[3][data]=3
columns[3][name]
columns[3][searchable]=true
columns[3][orderable]=true
columns[3][search][value]
columns[3][search][regex]=false
columns[4][data]=4
columns[4][name]
columns[4][searchable]=true
columns[4][orderable]=false
columns[4][search][value]
columns[4][search][regex]=false
columns[5][data]=5
columns[5][name]
columns[5][searchable]=true
columns[5][orderable]=false
columns[5][search][value]
columns[5][search][regex]=false
columns[6][data]=6
columns[6][name]
columns[6][searchable]=true
columns[6][orderable]=false
columns[6][search][value]
columns[6][search][regex]=false
columns[7][data]=7
columns[7][name]
columns[7][searchable]=true
columns[7][orderable]=true
columns[7][search][value]
columns[7][search][regex]=false
order[0][column]=7
order[0][dir]=desc
start=0
length=10
search[value]
search[regex]=false
action=all
unit=days
calendar=03 Jul 2019
hostname
browser=all
platform=all
timezoneOffset=-60
disposition
</pre>
</details>

**Comment by ScottHelme** [comment]
Hi @lol768, currently looking at this for you. Can you email me your registered email address so I can look at your account? scott[at]report-uri[.]com

@spaze I can't repro on my account, can you double check yours to see if we can narrow to a general error or perhaps account specific?

**Comment by lol768** [comment]
Cheers @ScottHelme, email sent

**Comment by ScottHelme** [comment]
A quick look turned up something that might be the culprit, can you check if this is working now @lol768?

**Comment by lol768** [comment]
Yup, that sorted it!

On a side note, is there a way I can see the raw user agent headers as sent in the original report?

**Comment by ScottHelme** [comment]
Ok, great to know that was the problem. What I've deployed is only a temporary fix and we'll need to look at something more permanent. @spaze I will raise an issue on our internal tracker. 

As for the UA string we don't log that right now but we are looking to extract more info like browser version in a later release. The concern is around identification of clients and when the data becomes PII/PD.

**Comment by ScottHelme** [comment]
A more permanent fix is now in place which I hope will address this issue. If it happns again please re-open!
