### ISSUE TITLE
Expect-CT reports of no value for Chrome versions 61 through 64

### ISSUE THREAD

**Issue by lol768** [report-uri/report-uri-bugs#111]
Following my email yesterday, I've isolated the `unknown` CT log reporting behaviour to Chrome versions 61 through 64 inclusive using Browserstack and testing on Windows. I can't verify that the reports we _do_ have in the report-uri account are from this version range, because the version number doesn't seem to be exposed - but I am reasonably confident this is probably the case.

I think for the service to be useful for Warwick, there would need to be some way to filter these spuroius reports out because they a) take up the quota needlessly and b) are not useful. I'm confident that SCT is being done properly at Warwick.

![image](https://user-images.githubusercontent.com/2552726/60656626-afc06900-9e47-11e9-98f3-c32d5f28a4cd.png)

**Comment by lol768** [comment]
Looking at this a bit more, I think the CT logs with which modern LE certs are logged to (and then embedded in the cert.) were not trusted/approved until March 2018 last year. See https://bugs.chromium.org/p/chromium/issues/detail?id=780655

If I'm not wrong, there is no out of band mechanism to update the CT logs which Chrome trusts

**Comment by lol768** [comment]
I think we're done here now @ScottHelme? From what Mat told me, work has been completed on your end - and it looks like it's filtering to me :smiley: 

Cheers for the assistance with this

**Comment by ScottHelme** [comment]
These are now indeed being filtered in production.
