### ISSUE TITLE
"The default team requires 2FA, please enable it first" [I have MFA enabled]

### ISSUE THREAD

**Issue by Get-Sleep** [report-uri/report-uri-bugs#115]
Default team feature was great but now when i login (after using MFA to login) i get this warning "The default team requires 2FA, please enable it first"

So i'm still not into the Team by default. And i'm not sure what to do about this error as MFA is definately enabled (confirmed in Settings). 

I'm using Google Authenticator.

**Comment by spaze** [comment]
Hi @Get-Sleep and thanks for the report. This was a stupid oversight on our side, and a missing test that would detect it sooner, sorry for that. The oversight was fixed and a test added so it won't happen again.

The fix should hit production any minute now, let me know if that worked for you. Feel free to close the bug if it worked.

Thanks again!
