### ISSUE TITLE
Required colon is missing

### ISSUE THREAD

**Issue by born2excite** [report-uri/report-uri-bugs#117]
The wizard does NOT add a colon to the schemas data and blob. I may be wrong but I believe a colon is required for both, data and blob schemas. Screenshot is attached for details.

Can you please check?

**Thank you!**

![Required colon](https://user-images.githubusercontent.com/10362816/64946514-67491100-d8b6-11e9-96a5-5e4b8f7e9a9f.png)

**Comment by ScottHelme** [comment]
This does look like it should have a colon, let me investigate!

**Comment by born2excite** [comment]
Thanks, Scott. You're a champ!

**Comment by born2excite** [comment]
Hey, Scott. I noticed the default-src directive has the value of self appearing 2 times ('self' self data). The first is enclosed in single quotation marks but the second has **no** quotation marks. Screenshot is attached for details. The second self value MAY be in relation to the data value. Can you please confirm if the second self value is correct without quotation marks?

![Missing required quotation marks](https://user-images.githubusercontent.com/10362816/65129761-57a90400-da3f-11e9-87a0-b2e5f0669612.png)

**Comment by ScottHelme** [comment]
The colon on data other URIs should now be resolved on the live site. Please let us know if you have any further issues!
