### ISSUE TITLE
DMARC Reporting not showing reports

### ISSUE THREAD

**Issue by slawa-dev** [report-uri/report-uri-bugs#118]
I have setup everything as the docs describe.
Reports are being sent to the email that is shown in Setup > DMARC Reporting
I can see reports are being sent to that email address in my logs. (I also get a copy)
But DMARC > Reports is empty

Delivered: noreply-dmarc-support@google.com → [*removed*]@dmarc.report-uri.com 'Report domain: [*removed*] Submitter: google.com Report-ID: 2885010166392666526' Server response: 250 OK

My account slawa [at] live . de

**Comment by fm** [comment]
Are you forwarding the reports from your server to Report-URI or are you specifying multiple mailto: in your policy?

**Comment by slawa-dev** [comment]
there is a single mailto in the policy (@mailgun .com) they are forwarded to report uri email and my personal email

**Comment by fm** [comment]
I wonder if the forwarder is messing something up. What happens if you try something like `v=DMARC1; p=reject; rua=mailto:postmaster@slawa.dev,mailto:user@dmarc.reporturi.com [...]`
