### ISSUE TITLE
10,000 report plan - change of month behaviour

### ISSUE THREAD

**Issue by alexcruice** [report-uri/report-uri-bugs#119]
## Timeline
**2019-09-30 10:50 AEST**
- email from notify@report-uri.com, "You have exceeded your quota"
- it took us the entire month of September to reach 10,000 reports
- roughly 60-40 split between CSP and NEL reports

**2019-09-30 15:01 AEST**
In reaction to the September notification, I made a couple of changes:
- removed our NEL header
- amended our CSP report-only header, changed the report-uri from the Wizard URI value to the Report-Only URI value

**2019-10-01 12:40 AEST**
- email from notify@report-uri.com, "You have exceeded your quota"
- somehow we've collected ~~12,000~~ reports in the first twelve hours of October
- that figure is now at 16,000 and rising (4,000 reports in the time it took to type this issue)

As much as I've love to think our web-app was that popular, I find it hard to believe. Our app metrics don't show any increase in usage. Have I misunderstood how the 10,000 report plan works?

**Comment by alexcruice** [comment]
What details are needed to assist with investigating this?

**Comment by ScottHelme** [comment]
Hi @alexcruice,

If you look on the CSP Reports page you should be able to see what the reports are that are coming in. Change the filter to Days and filter on 1st Oct. You should see what’s causing the problem and sending the reports. 

If you want to send me a screenshot, you can get me directly at scott@report-uri.com and I will take a look.
