### ISSUE TITLE
SRI hash generator says the response is not CORS enabled while it is

### ISSUE THREAD

**Issue by spaze** [report-uri/report-uri-bugs#12]
Hi,

I'm trying to use the SRI hash generator to hash https://www.michalspacek.cz/i/js/scripts.js
The generator says *The server does not have CORS enabled. This resource can't be integrity checked.* but the resource supports CORS when the requests is CORS-enabled.

```
spaze@snafuzer:~$ curl -s -i https://www.michalspacek.cz/i/js/scripts.js | grep Access
spaze@snafuzer:~$ curl -s -i --header "Origin: foo" https://www.michalspacek.cz/i/js/scripts.js | grep Access
Access-Control-Allow-Origin: foo
```

What seems to me is that you just check for the presence of the ACAO header but do not send the `Origin` header in the request. I might be completely wrong and sorry if I am.

Addin the `Origin` header should fix it, although I'm not sure what should be the value of it.

Thanks for looking into it!

**Comment by ScottHelme** [comment]
It seems you could be right. Give this a whirl: 

https://dev.report-uri.io/home/sri_hash/https%3A%2F%2Fwww.michalspacek.cz%2Fi%2Fjs%2Fscripts.js

**Comment by spaze** [comment]
Great, seems to be ok now, thanks a lot!

Closing this as **resolved**.

**Comment by ScottHelme** [comment]
This change has been pushed to master and will be deployed to production at 08:00 UTC.
