### ISSUE TITLE
Moving subdomain from personal to teams account doesn't work

### ISSUE THREAD

**Issue by hiburn8** [report-uri/report-uri-bugs#121]
When trying to migrate a CSP reporting subdomain from a free/personal account to a teams account, it seemed to work fine in the UI (after first removing it in the personal account). However the personal account (which then had a different subdomain) was/is still collecting data for the teams account. I've gone down the route of deactivating the private account... but the teams account doesn't seem to be able to start collecting data from this subdomain. Seems like a bug.

**Comment by ScottHelme** [comment]
Hi @hiburn8,

When you move a subdomain from a personal account to a team account did you notice that the reporting address also changes? It will change from /r/d/csp/enforce to /r/t/csp/enforce for example.

**Comment by hiburn8** [comment]
Oh s**t - my bad. I'll update the CSP and get more coffee.

**Comment by ScottHelme** [comment]
No problem, it's come up before which is why I suggested it first!

Please do let me know if that solves the problem for you and close this issue off. If not, I will be here to help if needed.

**Comment by hiburn8** [comment]
Yeahhhhhh.... working fine. Thanks for the fast reply, much appreciated.
