### ISSUE TITLE
Show NEL reports with referrer

### ISSUE THREAD

**Issue by SteveVaneeckhout** [report-uri/report-uri-bugs#126]
I'm seeing reports of 404 errors but it's impossible for me to find out which page contains the erroneous url. Other reporting websites show the referrer if it's available.

**Comment by ScottHelme** [comment]
The URL field of a NEL report should tell you the page it happened on, the referrer field would tell you where the user came from to visit that page. You can control whether or not we log the referrer value in reports on the Filters page 👍
