### ISSUE TITLE
SMTP TLS Filters Reversed

### ISSUE THREAD

**Issue by michaelkennedy** [report-uri/report-uri-bugs#129]
The filters on the beta SMTP-TLS reports feature seem to be reversed.

I have a small number of reports received. All reports indicate 100% total-successful-session-count, and have the Good status tick icon.

If I filter for "No Errors" I get "This search returned no results." I expect this filter to show all of the reports with a "Good" status.

If I filter for "Some Errors", "All Errors" or "Unknown" I see all of the reports received to date. All of these filters should return "This search returned no results"

**Comment by spaze** [comment]
Hi @michaelkennedy and thanks for the report. We've fixed the problem and deployed the fix now. We've also changed the default view and sorting for SMTP TLS reports to "month" and "by date" because it seems to make more sense in this case than day and by count.
