### ISSUE TITLE
Add ability to change account email

### ISSUE THREAD

**Issue by koluke** [report-uri/report-uri-bugs#13]
On the [account settings](https://report-uri.io/account/settings/) page, there doesn't appear to be an option to change the email address associated with an account.  I can only find options for changing the account password, updating the time zone, or disabling the account altogether.

I know this wouldn't necessarily be a high-demand or critical feature, but it would be nice to be able to change an account's email (if, for example, you lose access to the email used to register the account).

**Comment by LordMike** [comment]
If done. Beware of confirming the new account email. Also consider what happens if I transition from A to B, and before confirming the transition, I register a new account under email B. By confirming the transition I will effectively have to accounts with email B (which probably breaks some constraint).

**Comment by ScottHelme** [comment]
Hi @koluke, I will have a look at it, but right now you are free to create a new account with the new email address. The only problem here would be if you wanted to keep historic data, which would obviously be lost. I will see what's involved with allowing an email change, but unless it's easier than I think, it probably won't be high on the 'list of things to do' :-)

Thanks for the input @LordMike, with my use of Azure Table Storage I couldn't ever have two accounts with the same email as I use them as the RowKey and it effectively has a unique constraint on it.

**Comment by koluke** [comment]
Thanks for the quick reply @ScottHelme.  I wasn't too sure how difficult it would be, but I figured I'd ask anyway, especially since most websites allow you to change emails to accommodate users.  I completely understand it not being too high on your to-do list, particularly considering it wouldn't necessarily used that often.

Regarding @LordMike's comment, yeah, I'd think that changing the email would have a similar (if not identical) confirmation process as registering a new account.  From my experience, most web services won't let you confirm an additional email address if it's already tied to an existing account in their DB.

**Comment by LordMike** [comment]
This is typically because the email is a crucial part of their system. Many
things are tied to it that aren't immediately obvious: Rights, files, logs,
third party connections/integrations and so on.

In some systems, the email is the actual user identity. This means that
behind the scenes, it doesn't map to an ID but rather the "unique ID" /is/
the email. Changing an email is then a cumbersome procedure which in some
databases can't be done without removing and re-inserting data (chaing a
Primary Key value in MSSQL is a pain).

But sure. It's a nice feature :)

Mvh.
Michael

**Comment by ScottHelme** [comment]
After doing some further work on the site it'd honestly be easier for the user to create a new account and just move your subdomain over to the new account.

**Comment by dburry** [comment]
The result of this discussion is very disappointing to me.  After having the same email address for 20-30 years, and getting multiple 100's of spam messages per day, I will never do that ever again.  Now I change my email every year, by postpending the current year to it.  Friends who care to communicate with me via email adapt.  Previous years stay active as aliases for a few years, but eventually get dropped about the time when they show up in Troy Hunt's haveibeenpwned, as that's about the same time they start getting a lot of spam! (to be clear: Troy's not causing the spam, the public release of the email in a hacked database is... which is coincidentally also what's causing it to be included in Troy's site)

Anyway, please consider redesigning your site within the next few years, or I'll have to throw away my history every few years. (though, in fairness, I guess the very recent history is the most useful in fixing my problems, ancient history not as much, more of a curiosity of trending over time)

Also, one potential workaround, of course, is for me to create an email alias just for this site... (like, reporturi@mydomain.example) and then I'll only have to change that if Scott's site ever ends up getting hacked :)

**Comment by ScottHelme** [comment]
We should have this feature within the next week or so. Just waiting for final tweaks by @spaze :)

**Comment by dburry** [comment]
oh my! that's amazing :)

**Comment by ScottHelme** [comment]
It's live:

![image](https://user-images.githubusercontent.com/5352840/51075996-cb159d00-168a-11e9-93a9-e30907101022.png)


https://twitter.com/reporturi/status/1084131488420020224
