### ISSUE TITLE
POST https://magento1945rafaf.report-uri.com.report-uri.com/r/d/csp/reporting net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by rpfortes-redstage** [report-uri/report-uri-bugs#133]
Hey guys,

I'm not receiving any reports. When checking my browser's console I found the following:

![Screenshot_20200430_121018](https://user-images.githubusercontent.com/26420999/80727034-96c22c00-8adb-11ea-8761-67a789acd421.png)

**Comment by ScottHelme** [comment]
Hi @rpfortes-redstage,

Looks like there are a couple of things to solve. 

1) The reporting domain seems to be wrong, you have `magento1945rafaf.report-uri.com.report-uri.com` which should be `magento1945rafaf.report-uri.com` instead.
2) The path is `/r/d/csp/reporting` and should be either `/r/d/csp/enforce` or `/r/d/csp/reportonly`. 

Let me know if that helps!

**Comment by rpfortes-redstage** [comment]
It worked, thanks a lot, Scott!
