### ISSUE TITLE
Feature request: specify accounting email addresses

### ISSUE THREAD

**Issue by lstrojny** [report-uri/report-uri-bugs#134]
As a member of an accountant team, I would like to receive invoice emails automatically when the charge happens so I don’t have to wait for my oblivious CTO to send me the invoice "by hand".

**Comment by ScottHelme** [comment]
Hi @lstrojny,

Having a nominated billing contact is available on our Enterprise Plans but for our Standard Plans the invoice emails are automatically sent to the registered email address. There are a few options you could try that I've listed in the preferred order here:

1) Have your CTO setup an auto forward rule for any emails coming from our invoices@report-uri.com email address to automatically be sent to you.
2) Register an account with your email and subscribe to a Standard Plan and then invite your CTO to be a team admin and control the day-to-day operation of the account.
3) Subscribe to an Enterprise Plan and nominate a billing contact. 

Please let me know if I can assist further.
