### ISSUE TITLE
Not clear how many subdomains can be created

### ISSUE THREAD

**Issue by R3gi** [report-uri/report-uri-bugs#144]
I would like to maintain multiple websites. It's not clear if and how can I add multiple domains under my (free) account.

From the UX design of the Subdomain form I assume multiple domains can be added (there's a New subdomain field and button). When I "add new subdomain", my currectly used domain name is rewritten.

I searched the Docs, but there's nothing about managing multiple websites. I checked the Pricing tiles and it says "3 sites monitored" – so I expect I can monitor 3 different websites.

I think this should be clear from the UI, pricing  and from the Docs.

![image](https://user-images.githubusercontent.com/2983869/98035708-38269380-1e19-11eb-94bc-6bbd8e74c884.png)
![image](https://user-images.githubusercontent.com/2983869/98035857-6ad08c00-1e19-11eb-8bcf-261e7b204253.png)

**Comment by ScottHelme** [comment]
Hi @R3gi,

You have a single domain to send reports to for all of the sites you monitor. 

You can configure the sites you collect reports for on the Filters page: https://report-uri.com/account/filters/

There is a section "Global Report Filters" and in there is a "Sites to collect reports for" section. On a free account you are limited to only 3 sites in this field. 

This is detailed in our docs on the main page: https://docs.report-uri.com/

Under the "Filters" heading we have the following: "For most sites the default selection on the Filters page are generally good to go **but you do need to provide us a list of which sites you'd like to collect reports from**."

Cheers, 

Scott.

**Comment by R3gi** [comment]
Hi @ScottHelme,
thanks for quick and detailed answer. Does this apply to the CSP Wizard too? In other words, will be possible to distinguish collected values from certain domains in the Wizard? (If not, it's okay to collect them one by one, just asking :-))

I still thing this is a bit confusing in the UI. But maybe I'm just "special".

**Comment by ScottHelme** [comment]
Hi @R3gi,

The CSP Wizard is only intended to be used on a single site at a time due to the volume of reports it can generate. As such the UI does not have the ability to distinguish between which site is using it. The CSP Wizard has a unique reporting address so you would only configure a single site to send reports there. Those reports are in a separate section of the UI so you can always distinguish them from normal reports. 

Cheers, 

Scott.

**Comment by R3gi** [comment]
Okay, thank you very much for your kind help.

I assume it isn't necessary to keep this ticket open, but feel free to reopen it if you want to use it as feedback to the UI :-)
