### ISSUE TITLE
CSP report only POST request shows 201 response, but no CSP reports are displayed in Dashbaord 

### ISSUE THREAD

**Issue by dingjiedanielyang-sec** [report-uri/report-uri-bugs#159]
Hi Team,

I am testing the CSP feature under report-uri. I do notice that the violations are reproted to the report-uri endpoint and the response code is 201. However, there is no reports displaying under dashboard even 10 minutes after the violation was reported to the report-uri endpoint.
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/48067965/144944479-a5a3ffb4-647c-4ad6-8f7d-de4ce8df8406.png">

I am hosting the application under localhost for test purpose. I am not sure the localhost is filtered out somehow.

Thanks

**Comment by ScottHelme** [comment]
Hi @dingjiedanielyang-sec,

You can check on your account Homepage: https://report-uri.com/account/

If you are seeing reports with the Filtered or Rejected action then they will not show in your account and something is causing them to be removed. If you see them as Accepted then they should be visible in your account. Can you let me know what you see?

Cheers,

Scott.

**Comment by dingjiedanielyang-sec** [comment]
Hi Scott,

I saw some CSP reports are rejected. I am using report only mode. I am not sure why these are rejected. Could that be caused by some filtering. (I am using default setting)
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/48067965/144947116-c0c1fbb6-ac56-49b5-954f-797270109e70.png">


Best
Daniel

**Comment by ScottHelme** [comment]
Please email directly and we can investigate further for you, scott@report-uri.com
