### ISSUE TITLE
Alerting System

### ISSUE THREAD

**Issue by scarytom** [report-uri/report-uri-bugs#165]
I guess you would class this as a feature request.

I've been looking at your main competitor (https://www.uriports.com/) and they offer email notifications and instant notifications of significant events via Telegram.

Are you hoping to offer any kind of alerting from report-uri?  I'd be interested in anything from email notifications to full-on integrations with popular tools like Slack.  Looking through your other GitHub issues, it seems a few people have mentioned this, but I couldn't find a dedicated issue.

As an aside, it seems like a lot of the issues here are quite old and haven't seen any traction.  Is report-uri under active development at the moment?

**Comment by ScottHelme** [comment]
Hi @scarytom,

Our docs cover the areas where we currently have email notifications for events, which include [Script Watch](https://docs.report-uri.com/setup/script-watch/), [Data Watch](https://docs.report-uri.com/setup/data-watch/), and [Certificate Transparency](https://docs.report-uri.com/setup/certificate-transparency/). 

This tracker is an older system that we don't really use now, it's best to contact us directly. You can email me if you'd like (scott@) and I'm happy to answer any questions.
