### ISSUE TITLE
Change HTML Title of Login page

### ISSUE THREAD

**Issue by chrisemerson** [report-uri/report-uri-bugs#17]
My password manager uses the window title to auto-fill login information from my password database, and it can't differentiate between this site and many others at the moment as the title is just 'Login'.

Could you change the title to include the website name somewhere as well?

**Comment by ScottHelme** [comment]
Which password manager is this? Using the page title seems very odd!

**Comment by chrisemerson** [comment]
KeePass. It uses window titles, and browsers tend to use the page titles there. It doesn't just work for websites and I'm guessing it has no access to the URL of any page/site loaded in a browser.

**Comment by ScottHelme** [comment]
Does that not mean if I setup a website somewhere else that had the same title, it would potentially input the username/password on the wrong site if it copied the page title?

**Comment by chrisemerson** [comment]
I have to hit a key combination for it to do anything, so that would be up to me to ensure I'm on the right site before doing so - no different to entering a username and password myself.

**Comment by ScottHelme** [comment]
Wow, that seems really risky! Your password manager would betray you on a convincing phishing page and insert your creds. 1Password (which I use) will check the URL of the page is correct so this can't happen. 

Either way, I've added this to the dev site so it will filter through test and then into production soon.

https://dev.report-uri.io/login

**Comment by chrisemerson** [comment]
No - like I say, I would have to press the key combination for it to insert any information, and I wouldn't do that on a phishing site. And if I would... then I'd be typing my details in ordinarily myself anyway. It's no more risky than without the password manager.

**Comment by LordMike** [comment]
Well. Lastpass too works as an extension, which works using the URL of the website in question. Lastpass and 1Password seem way more oriented towards webpages, where KeePass seems like a general solution that would work for regular apps too (hence the window titles).

In Lastpass/1Password it would be very unlikely that you would ever enter credentials on a phishing site. The plugins could even help you identify one, when they "fail" to autofill or suggest saved passwords. I was once wondering why LP failed to autofill, only to find out that the target site had (legitimately) been embedded in an iframe... Which is phishy :)
