### ISSUE TITLE
"Create your SRI hash" page recognises available https but doesn't use it

### ISSUE THREAD

**Issue by gbz101** [report-uri/report-uri-bugs#20]
If the web address entered at https://report-uri.io/home/sri_hash, is entered, starting with http://code.jquery.com/, the webpage comments "We upgraded the protocol to HTTPS as code.jquery.com is a known secure host." but the code supplied in the box for copying and pasting still starts: <script src="http://code.jquery.com/, rather than <script src="https://code.jquery.com/.

**Comment by ScottHelme** [comment]
This should now be fixed on dev:

https://dev.report-uri.io/home/sri_hash/http%3A%2F%2Fcode.jquery.com%2Fjquery-3.1.1.min.js

I will close this issue and the fix will filter to test and then prod shortly.
