### ISSUE TITLE
ignore double spaces in csp header

### ISSUE THREAD

**Issue by gemal** [report-uri/report-uri-bugs#22]
If you use:
https://report-uri.io/home/analyse/
and check:
https://911.dinnerbooking.com/

![skaermbillede 2016-12-09 14 40 12_cr](https://cloud.githubusercontent.com/assets/69105/21050878/8bb9f3a8-be1d-11e6-93cf-1a09c77f4aee.png)

you will get some empty entries in the result.
This is due to space in the CSP header
I think you should ignore those spaces

Note the 2 spaces before "maxcdn"

`default-src 'self'  maxcdn.bootstrapcdn.com; script-src 'self' data: 'unsafe-inline' www.google-analytics.com www.google.com maxcdn.bootstrapcdn.com ajax.googleapis.com; style-src 'self' 'unsafe-inline'  maxcdn.bootstrapcdn.com; img-src 'self' data: www.google-analytics.com; report-uri https://dinnerbooking.report-uri.io/r/default/csp/reportOnly`

**Comment by ScottHelme** [comment]
This is now fixed on the dev site and will work through test into production.
