### ISSUE TITLE
Generate policy based in report-only caught violations

### ISSUE THREAD

**Issue by jessehouwing** [report-uri/report-uri-bugs#24]
In order to build a policy in the as-is state, it would be easy to turn on  reporting, wait a week and then use that as a baseline for the policy. Just go to report, select a date range and hit open in policy builder

**Comment by ScottHelme** [comment]
We currently have this feature in development and hope to release in Q1 2018.

**Comment by ScottHelme** [comment]
The CSP Wizard should now cover this for you.
