### ISSUE TITLE
Feature Request: Export All Report

### ISSUE THREAD

**Issue by Jxck** [report-uri/report-uri-bugs#26]
Hi
I wanna Export All Report from report-uri.io as file to local.
Do you have in mind to support this ?

**Comment by ScottHelme** [comment]
I don't actually keep all historic data in the service and roll it up on regular intervals. There are more details outlined in my blog:

https://scotthelme.co.uk/introducing-sensible-limits-to-report-uri-io/

I could create an export function to export what I have but I'm not sure it'd be high on the list. It's quite an expensive query (time and cost) and I'm not sure what value it'd provide. Could you let me know why you think it'd be useful?

**Comment by ScottHelme** [comment]
Closing as no response.

**Comment by dorianmariefr** [comment]
I would need this too, I would like to search for non-matching (kinda like `grep -v`), e.g. not a domain
