### ISSUE TITLE
New entries for "Filter out unactionable CSP violations".

### ISSUE THREAD

**Issue by nico3333fr** [report-uri/report-uri-bugs#28]
Hi there,

here are some suggestions for completing this list, taken from this https://github.com/nico3333fr/CSP-useful/tree/master/csp-wtf :

Source-File :
- "chrome-extension://"
- "safari-extension://"
- "se-extension://"

Blocked URI: 
- "android-webview"
- "safari-extension://"
- "opera://js-inject" && "http://adblockers.opera-mini.net"
- "ms-browser-extension"

I still have a lot of CSP notifications to sort, anyway it is a good start. :)

I'm wondering if you want to add more filters categories, for example for some devTools (https://github.com/nico3333fr/CSP-useful/tree/master/csp-wtf#devtools- or https://github.com/nico3333fr/CSP-useful/tree/master/csp-wtf#function-installglobalhookwindow), or some other extensions (Digg https://github.com/nico3333fr/CSP-useful/tree/master/csp-wtf#digg , Ghostery https://github.com/nico3333fr/CSP-useful/tree/master/csp-wtf#ghostery, etc. ) ?

If so, I may provide some more or you may pick up on my repo.

Cheers,
Nicolas

P.S : only curiosity: for your existing filters, do you have any source from where they are coming from ? (I've never seen some of them in my reports, like chromenull://, mxjscall:// , etc.)

**Comment by ScottHelme** [comment]
"do you have any source from where they are coming from"
Currently processing ~87,000,000 reports a day ;-)

**Comment by nico3333fr** [comment]
> Currently processing ~87,000,000 reports a day ;-)

Okay :'-)

My english is terrible, I wanted to say: do you know what caused them on the websites ? ;)

(it is a bit difficult to find informations about CSP issues sometimes)

**Comment by ScottHelme** [comment]
Ahh gotcha, sorry. I generally do some digging into them to understand what caused them before I add a filter but I don't keep a record of that. I probably should...

**Comment by ScottHelme** [comment]
Added the rest of these to the dev site after extended testing. They will hit live soon.

**Comment by tanto259** [comment]
Hi, are these changes live already?
I just get several CSP violation from `https://adblockers.opera-mini.net`

**Comment by nico3333fr** [comment]
@tanto259 I just noticed that I suggested "http://adblockers.opera-mini.net" and you have "httpS://adblockers.opera-mini.net". 

I just updated my parser to avoid it https://github.com/nico3333fr/CSP-useful/blob/master/report-uri/csp-parser-enhanced.php#L251
