### ISSUE TITLE
Add a Test Button in the Console

### ISSUE THREAD

**Issue by richardjgreen** [report-uri/report-uri-bugs#29]
report-uri.io is a great service and greater that it's free right now. I put a lot of time and effort into getting my CSP and HPKP just right on my site so that no errors are generated. 

Whilst it is entirely possible to manually test that the URI for CSP and HPKP are present using the the CSP Analyzer and HPKP Analyzer, it would be nice to have a test button in the console that you can press, it performs an automated CSP and HPKP check and validates the URI against the URI configured in the account Setup page.

**Comment by ScottHelme** [comment]
Even if I used collect hosts I still wouldn't know the scheme to check for the site/s. 

I am thinking about adding a marker to the CSP analyser tool to highlight that you use report-uri.io though!
