### ISSUE TITLE
Would it make sense to support DMARC reports as well?

### ISSUE THREAD

**Issue by evaryont** [report-uri/report-uri-bugs#34]
It'd be neat, I'd think. Though it would require some way to accept incoming emails.

Documented in detail in [RFC7489](https://tools.ietf.org/html/rfc7489)

**Comment by LordMike** [comment]
I'd actually say it wouldn't here.. Where Report-URI has its great advantage that nobody really supports the report types on a large scale (being a first mover is great), it's not so with DMARC.

Supporting DMARC reports would be a whole new beast (new layouts, new UI, new interpretations of data, new grouping/filtering etc..), new search capabilities (DMARC reports contain a wealth of data that we want to dive into).

For DMARC, I'd always recommend Dmarcian (US: https://dmarcian.com - EU: https://dmarcian-eu.com/). They have free plans, support the wealth of information that DMARC reports contain, and they have the analysis tools needed to dive into it.

No need to do double work :).

**Comment by ScottHelme** [comment]
I'm in agreement with the above comment. Looking around there are plenty of good DMARC services :)
