### ISSUE TITLE
Error message: "Could not complete request. Please check your internet connection"

### ISSUE THREAD

**Issue by KommX** [report-uri/report-uri-bugs#35]
I get this message often when I want to see some CSP reports.
My internet connection is working just fine. I have the feeling I'm getting this message more often when there will be more results ("Days" instead of "Hours").

![report_uri](https://user-images.githubusercontent.com/7859245/28499696-026f2428-6fbc-11e7-9bf2-53ede5a8d81e.png)

**Comment by ScottHelme** [comment]
If you're still experiencing this issue on the new site then please re-open a new bug.
