### ISSUE TITLE
HPKP Analyzer: Detect hashes for RSA and ECC handshakes

### ISSUE THREAD

**Issue by Ayesh** [report-uri/report-uri-bugs#36]
Hi Scott,
Minor nitpick. 

The HPKP analyzer is pretty awesome and works well outright. I have a setup the the web server serves an RSA certificate if the client does not support EC certificates. Right now, it marks the RSA cert hash as a backup key when it is actually in use, just not for that ECC handshake. 

Thanks!

**Comment by LordMike** [comment]
I suppose Cloudflare will do the same?

**Comment by Ayesh** [comment]
> I suppose Cloudflare will do the same?
Sending RSA and EC certificates based on client? yep.

**Comment by ScottHelme** [comment]
Given the pending deprecation of HPKP by Chrome I'm going to mark this as won't fix. 

https://scotthelme.co.uk/im-giving-up-on-hpkp/

https://scotthelme.co.uk/the-death-knell-for-hpkp/
