### ISSUE TITLE
Feature request: Offer sandboxed preview option

### ISSUE THREAD

**Issue by jessehouwing** [report-uri/report-uri-bugs#39]
We found a number of hits in one of the sites recently, the hits include `data:` images and it took us a while to figure out these were inserted by Pinterest. Extracting the base64 encoded string, decoding it, saving it as the right type and showing it (and then recognising the logo) took quite a bit of time.

It would be lovely if a sandboxed iframe or popup window would show images.

It would be lovely if a plain-text rendering of CSS and JS files were provided.

I understand there may be security implications, so this may need to be loaded from do-not-trust.report-uri.io and be rendered in a sandboxed iframe with no script, form and other permissions.

**Comment by ScottHelme** [comment]
This is an interesting one as the browser really shouldn't be sending the base64 encoded asset. That makes reports pretty big and I'm not sure it's spec compliant behaviour. Do you have some examples reports you can share privately with me Jesse?

**Comment by jessehouwing** [comment]
Hmmm... I received the report from the devs involved. It looks like report-uri is indeed not receiving this from the browser. So that makes sense base don the specs. It's a shame though, as it really helps with identifying the source of the issue. Hmz

**Comment by jessehouwing** [comment]
Further asking they managed to locate the page and asked a user to check the browser log. Firefox and Chrome do log the data uri to their console.

**Comment by ScottHelme** [comment]
I can understand logging to the console as there's no network penalty and it helps with debugging. I'd be surprised if we were getting base64 assets at the service though.

**Comment by jessehouwing** [comment]
I'd still love it :) /close.
