### ISSUE TITLE
Unrecognized Content-Security-Policy directive 'referrer'

### ISSUE THREAD

**Issue by mdmcginn** [report-uri/report-uri-bugs#41]
My Chrome Dev Tools console says "Unrecognized Content-Security-Policy directive 'referrer'." It seems to be referring to a line generated by your CSP Builder:  referrer no-referrer-when-downgrade; 

The error disappears when I remove that line. I get the same error with referrer origin-when-cross-origin;

**Comment by ScottHelme** [comment]
Some browsers support the directive and others don't, it depends on which version of the CSP spec they are compliant with. I believe referrer is being deprecated in favour of the Referrer-Policy header though so you can remove it and implement that instead:

https://scotthelme.co.uk/a-new-security-header-referrer-policy/
