### ISSUE TITLE
Feature request: noise generated by Trusteer Rapport (nikkomsgchannel)

### ISSUE THREAD

**Issue by bencromwell** [report-uri/report-uri-bugs#45]
We're seeing reports for `connect-src` pointing to URLs like this one:

```
https://nikkomsgchannel/e?001c0050002d00500036004300680053005e0024002f005700560009002400410022005d0052006f005f0021007c000100150050002d00500036004300520054000b00310033004500560010002700450026005e0043006f005b0024002600590050000b007a000600750005000f000200070006007600730076000e0064005d0022005d0052000d0043003600240042005d0057002f005600650044004e00400053007800350055004b004200640055002c0042005a000d0058002c002a005b005c0058002b005f002f
```

[This SO question](https://stackoverflow.com/questions/44407729/csp-connect-src-https-nikkomsgchannel) points towards Trusteer Rapport being the culprit. 

It would be great to have this included in the "Filter violations caused by browser extensions".

**Comment by ScottHelme** [comment]
I've taken a look at the data and we've updated the extension filter to remove these reports. Thanks for letting us know!
