### ISSUE TITLE
Safari extension Shopicks (?) causing CSP violation reports

### ISSUE THREAD

**Issue by yvanavermaet** [report-uri/report-uri-bugs#47]
Hi

In my filter-settings, "Filter violations caused by browser extensions" is active. However, I see a lot of reports with "safari-extension://com.shopicks.safari-52637h29am" as blocked URI for the font-src directive.

As requested on Twitter, I created this bug report.

Kind regards,
Yannick

**Comment by ScottHelme** [comment]
Hi Yannick,

Can you check if this is still happening? We did have a bug in the filters that was allowing some reports through that should have been filtered.

Thanks!

**Comment by yvanavermaet** [comment]
Hi @ScottHelme 

Apologies for the late reply. No errors have occurred since then. Thanks for resolving the issue.

Kind regards,
Yannick
