### ISSUE TITLE
Add chrome-error to ignored browser protocols

### ISSUE THREAD

**Issue by cmbuckley** [report-uri/report-uri-bugs#48]
Reference discussion: https://groups.google.com/a/chromium.org/forum/#!topic/extensions-reviews/6EEDB0fNJ6U

Chrome error pages now have their own scheme, ironically in order to prevent error pages inheriting the parent page's CSP.

I believe this should be excluded from reports using the browser filter section.

**Comment by ScottHelme** [comment]
Got it, thanks for the tip, I've highlighted this for inclusion.

**Comment by cmbuckley** [comment]
Thanks, really loving the tool!

Where do you recommend for more general CSP discussion, browser-specific quirks or not following standards etc?

**Comment by ScottHelme** [comment]
If the browser isn't following the spec you should absolutely bug it on the appropriate bug tracker. Feel free to cc me on any of those. 

As for wider discussion on CSP 3, probably these issues and the associated repo: https://github.com/w3c/webappsec/issues

Also a great resource for browser quirks here by @nico3333fr: https://github.com/nico3333fr/CSP-useful

**Comment by ScottHelme** [comment]
I've just added the filter and the change will hit production at 15:00 UTC.
