### ISSUE TITLE
CSP hash generator does not generate valid hashes

### ISSUE THREAD

**Issue by DanielRuf** [report-uri/report-uri-bugs#49]
I tried to copy and paste the script block from https://daniel-ruf.de/ but it seems it is always wrong in my case.

Chrome gave me another hash in the console which works.

**Comment by ScottHelme** [comment]
Could you provide the script you tried to hash and the values provided by our site and Chrome for me to test? Thanks!

**Comment by DanielRuf** [comment]
I tried to copy and paste the script from https://github.com/DanielRuf/daniel-ruf.de/blob/master/index.html#L61-L92. 

I've used https://report-uri.com/home/hash which gave me a hash of `sha256-au5TPq3lBxHNAfaO29HV0vB5WIABppYAu1iYxxLBacw=` or `'sha256-TcFneV4Br8nrTHDFPZ9p5wb6EjTMd4+bsh5ckm7n9+g='`

Chrome 62 did not accept it. After some testing Chrome suggested `'sha256-05x90pOXEro9aNI8O/0EEGI+Ae0JPBr5AbwDODZ6+tg='` which seems to work.

Did I oversee some script or was it really wrong? Do the EOL in the file, the file encoding and so on matter?

**Comment by ScottHelme** [comment]
If I copy the script element from your site and hash that I get the same value that Chrome is providing:

![image](https://user-images.githubusercontent.com/5352840/34468741-2d1f2aa4-ef07-11e7-97d7-127cee4ea350.png)

If I copy and paste from GitHub then I get the value you're providing:

![image](https://user-images.githubusercontent.com/5352840/34468747-62ed6768-ef07-11e7-8fa5-6d9f6b55bbe9.png)

It seems that the indentation between the two is different. Ideally you should externalise this script into a file and load it from your own domain rather than load it inline. You can also minify the asset to save on bytes and avoid issues with hashing like this.

**Comment by DanielRuf** [comment]
> If I copy the script element from your site and hash that I get the same value that Chrome is providing:

I tried from the view-source and pure file. Seems it is only releant how it is in the actual DOM (element tab in the DevTools)?

**Comment by DanielRuf** [comment]
The indentations are the same. At least I just do `git pull` on my server and that's all.

**Comment by DanielRuf** [comment]
> It seems that the indentation between the two is different. Ideally you should externalise this script into a file and load it from your own domain rather than load it inline. You can also minify the asset to save on bytes and avoid issues with hashing like this.

In general this would make the performance worse and influence the (critical rendering path) CRP ;-)

**Comment by DanielRuf** [comment]
Did you add a newline at the start and end? It looks like there are two empty lines extra in your first screenshot.

**Comment by ScottHelme** [comment]
No, those newlines were present as a result of copying the element:

![image](https://user-images.githubusercontent.com/5352840/34468798-6ab140ea-ef08-11e7-989a-7fae0814c321.png)

**Comment by ScottHelme** [comment]
If I do it from the view source window I get another, different value: 

![image](https://user-images.githubusercontent.com/5352840/34468801-79408f3a-ef08-11e7-989b-860b8d5bdb7a.png)

**Comment by DanielRuf** [comment]
> If I do it from the view source window I get another, different value:

Because of the two missing newlines ;-) So the validator needs these two?

**Comment by ScottHelme** [comment]
Chrome must be basing its hash on those two newlines being present so the tool will also need them to generate the same hash value. 

You should minify it to shrink your page too ;-)

**Comment by DanielRuf** [comment]
In general it would be helpful to have some examples for the generator to see how the input should be normally.

**Comment by DanielRuf** [comment]
I did not know that these two etra lines are actually needed =) Thanks for taking a look.

Can I close the issue?

**Comment by ScottHelme** [comment]
The input needs to be exactly as the browser interprets it to generate the hash so we can do the same. This newline thing is odd and new to me. I just tried it out on my site: https://scotthelme.co.uk/csp-test/

    <script>alert("Stuff");</script>

This requires a hash of sha256-Lo/E+TX5i16CaXerKef5L0a3uIs2Agl2DUnre4TiPcs= which the tool generates properly. If I newline the script tag content:

    <script>
        alert("Stuff");
    </script>

I need to add the newlines at the start and end of the input to the tool to get the right hash. Also confirmed in Firefox.

It seems things are working as expected!

**Comment by DanielRuf** [comment]
Ok, makes sense then.
