### ISSUE TITLE
Send invited users an email

### ISSUE THREAD

**Issue by jessehouwing** [report-uri/report-uri-bugs#54]
When a user is invited to a team, but when that users doesn't have an account yet:

 * [x] Send that user an invite to join the account
 * [ ] skip subdomain creation & filter configuration
 * [ ] make the team which invited the user the default user

**Comment by ScottHelme** [comment]
Users are now sent an email when invited to a team to notify them that they are able to use that team. 

We probably won't take on tasks 2 and 3 for now as they represent quite a change in the logic of account creation/setup. The user can just ignore/skip these steps.

We may add the option for a user to select a default account/team at login at some point in the future.
