### ISSUE TITLE
Save reports query

### ISSUE THREAD

**Issue by jessehouwing** [report-uri/report-uri-bugs#58]
It would be great if we could save multiple report filters and when we could combine multiple report filters. We have a large site and we'd like to create a number of canned queries that people can use to quickly look for certain issues. Having a counter on them (like a Gmail inbox folder) would be nice as well.

Being able to copy the URI of a report page so that we can drop it in a slack channel or email would also be helpful. 

Being able to copy a link to a specific report on a filtered report would also be nice.

**Comment by ScottHelme** [comment]
Hey Jesse, 

We've added the filter settings to the query string now so they can be copied/shared/bookmarked at your leisure. 

We do have a  longer term feature idea for storing queries in the service but for now I will close this issue as most of the requests have been addressed. 

Thanks!
