### ISSUE TITLE
Inviting users who have a case-sensitive address

### ISSUE THREAD

**Issue by jessehouwing** [report-uri/report-uri-bugs#61]
The fix for https://github.com/report-uri/report-uri-bugs/issues/60 resolved the problems when inviting users who registered with a mixed case email address.

It looks like there are at least two more places with issues:

 * [x] When signing on to the service the email address should be normalized (So: `Jesse@example.org => jesse@example.org`
 * [x] When checking Team membership, the email address comparison should be normalized. `{Jesse@example.org, other@example.org} contains jesse@example.org => true`

**Comment by ScottHelme** [comment]
According to the RFC we can't normalise addresses quite that aggressively. Whilst the domain portion can be normalised to all lowercase, the alias prior to the @ symbol is case-sensitive. 

https://tools.ietf.org/rfc/rfc5321.txt

**Comment by jessehouwing** [comment]
This may cause interesting issues with people... Outlook.com, Gmail.com and most other email providers do not enforce this and route all email regardless of case to a single inbox. I'd almost consider it a security problem that I could register Tim@example.org and tim@example.org to actually be two different accounts. After registering the upper case version (which doesn't require email validation immediately), I could contact a team admin to "fix my team membership".

I suppose that most admins aren't even aware of the distinction and will happily swap my access over. This is a very dangerous fishing angle.

For our private instance, we use Office 365. We know for sure that all email is case insensitive. Any way to enforce this for one or more TLD's in the instance?

**Comment by ScottHelme** [comment]
The flip side of that is that we don't know if the email provider is case sensitive or not. Let's say that we assume all email addresses are lower case but you use `fake-mail.com` who are case sensitive. Your email address is `Jesse@fake-mail.com` but we force lower case and send your emails to a different account, `jesse@fake-mail.com`. The same method of phishing above could also work by me registering a similar address to yours and claiming I need it updating etc... 

I see what you mean, but I think we need further investigation, I'm not sure I know enough to make a decision.

**Comment by ScottHelme** [comment]
We've looked into this and taken into account the behaviour of other services and email providers. I've just approved a change that will add the normalisation behaviour above. Let me know how you get on!
