### ISSUE TITLE
Reports counted on dashboard, but don't appear elsewhere

### ISSUE THREAD

**Issue by C4K3** [report-uri/report-uri-bugs#62]
I just setup CSP in report-only using report-uri.com. On the main dashboard I see 118 CSP reports as accepted and processed. But when I click CSP and reports, it says there are no results. Even if I set the date for all of February and click Filter, it doesn't show any.

If I click graphs for CSP, it's just a constant 0.

Is this a bug, or have I misunderstood something? Do I need to wait longer for them to appear?
![reporturi1](https://user-images.githubusercontent.com/4582830/36630709-a2c00046-1962-11e8-8ac0-2c2037000f1d.png)
![reporturi2](https://user-images.githubusercontent.com/4582830/36630710-a2e4239a-1962-11e8-9a5c-da819aa6df1f.png)
![reporturi3](https://user-images.githubusercontent.com/4582830/36630711-a3067cec-1962-11e8-9f06-926d273cc43f.png)

**Comment by ScottHelme** [comment]
A quick thing to check is whether your account is activated. On the account homepage do you see any remaining steps above the green CSP count?

**Comment by C4K3** [comment]
That was it, I thought I had activated because I did get and extract the link, but apparently it didn't register (I have html disabled in my email client, so I probably got the link incorrectly.) But after opening the email with Firefox, I clicked the link again and then it fixed it.

I can see new reports now, so everything seems to be working :) Thanks for the service!

**Comment by ScottHelme** [comment]
No problem, enjoy!
