### ISSUE TITLE
Hit back to go to filtered CSP report gives date/time parse error

### ISSUE THREAD

**Issue by jessehouwing** [report-uri/report-uri-bugs#66]
I configured a report to show the month of March and then I clicked on the CSP Graph.

Then I hit Back in the browser, the page loaded and I'm greeted with a Date/Time parse error. The Month filter seems to have carried over, but the time textbox has reset itself to This date + hour.

Error below:

![image](https://user-images.githubusercontent.com/4173387/37619258-398d85f8-2bb9-11e8-96e7-ba2ea50f494f.png)

Steps to repro:
* Open the CSP Report page
* Configure the Date filter to Month
* Set a specific Month
* Navigate to CSP Graphs
* Hit `Backspace` / `Alt` + `<-` / Browser back to go back

**Comment by spaze** [comment]
Hey @jessehouwing, thanks for the report. This has now been fixed and deployed to production.
