### ISSUE TITLE
Safari 11.0.3 Reporting Stalls

### ISSUE THREAD

**Issue by bsdkurt** [report-uri/report-uri-bugs#72]
Using macOS High Seirra 10.13.3 + Safari 11.0.3 (13604.5.6) CSP policies with report-uri stall and don't create reports in report-uri.com. I've tried various CSPs but they all seem to stall. I am currently using the recommended starting wizard CSP of:

`Content-Security-Policy-Report-Only: default-src 'none';frame-ancestors 'none';form-action 'none';report-uri https://{subdomain}.report-uri.com/r/d/csp/wizard`

Firefox and Chrome report ok but safari just stalls (see attached image and note the lack of a reply and long execution times).

**Comment by bsdkurt** [comment]
![image](https://user-images.githubusercontent.com/4834782/38556717-a28f021c-3c98-11e8-836b-2891e81973e3.png)

**Comment by ScottHelme** [comment]
I have a bug open on the WebKit and Apple bug tracker for this:

https://bugs.webkit.org/show_bug.cgi?id=173314

https://bugreport.apple.com/web/?problemID=36986561

**Comment by bsdkurt** [comment]
Hi Scott,

Thank you for the quick reply. I thought perhaps this was a problem with the endpoint, but your bug report indicates they are not being sent at all. Closing this since it is not a report-uri.com issue.

**Comment by ScottHelme** [comment]
Yeah it's a bit of a pain and you will see on the bugs it's not the first time this has happened. I will keep pushing them for a fix!
