### ISSUE TITLE
Navigation between pages is confusing when reporting data to a team

### ISSUE THREAD

**Issue by stof** [report-uri/report-uri-bugs#73]
I'm currently reporting all the data to a team, having no data at all in the "personal team". And here is what I see when navigating on report-uri for my personal account:

- `home is showing numbers taking the team data into account
- `CSP > reports` is empty (quite expected, as all data is in the team)
- `CSP > graphs` is showing stats including the team data
- `CSP > wizard` is empty

**Comment by ScottHelme** [comment]
Hey @stof, thanks for raising this! 

Just wanted to confirm that I can repro this in some circumstances and I've raised this internally, we're working on a fix.

**Comment by ScottHelme** [comment]
Hey @stof, we've just deployed a fix for this which will be live shortly.

It won't remove old data from the graphs page but it will stop new team data appearing in your personal graphs. Nothing to do with billing or quotas was affected.

Let me know how you get on and close this issue if you're happy!

**Comment by ScottHelme** [comment]
Closing this issue. Please re-open if you have further problems!

**Comment by stof** [comment]
I confirm that the graphs are clean for the last few days in my case.
