### ISSUE TITLE
"Filters" tooltip not compatible with Reports' "URI Filter"

### ISSUE THREAD

**Issue by KommX** [report-uri/report-uri-bugs#75]
In the tooltip of "Filters" --> "Sites to collect reports for" there is the following sentence:

> Do not specify a scheme or a subdomain like 'www'.

But when you follow this guideline and have sites like `www.example.com` the "URI filter" on CSP --> Reports won't match the www subdomains.

**Comment by ScottHelme** [comment]
Hi @KommX, 

On the Filters page you should only specify `example.com`.

On the Reports page you can search for any subdomain you like. Values you can search on include `example.com`, `www.example.com`, `anything.example.com` or even `*.example.com`.

There are more details in our docs here: https://docs.report-uri.com/help/search/
