### ISSUE TITLE
Feature request: show sample report payloads in wizard

### ISSUE THREAD

**Issue by valorin** [report-uri/report-uri-bugs#79]
The wizard only presents the raw domain name and directive, and expects you to be able to identify if it should be allowed or not. For most domains this is trivial, but in some cases, you may want to know why a specific domain is being used. Having the ability to view some of the payloads sent would provide this context to make a more informed decision.

In one specific case, I can see `default-src gist.github.com` listed in the wizard. I would love to know two things about this:

1. Is it only requests to my gists subfolder ('gist.github.com/valorin/`)?
2. why is it `default-src` instead of `script-src` or whatever else it could be?

**Comment by valorin** [comment]
To add to this, the wizard keeps reporting `img-src 'self'` as needed, but it's in the report-only CSP already, and all other rules are being honored. It would be great to be able to see some of the raw reports, in order to debug why it's showing up.

**Comment by ScottHelme** [comment]
If you wish to see the reports and use the Wizard you can duplicate your CSPRO header and have one report to /wizard and one report to /reportOnly. For now, this would be the only way to achieve visibility in the Wizard and Reports pages.

**Comment by valorin** [comment]
Ah! That makes a lot of sense, I didn't realise you could duplicate the header like that. Thanks @ScottHelme  😀

**Comment by ScottHelme** [comment]
No problem, glad I could help.
