### ISSUE TITLE
unfiltered font-src for chrome-extension

### ISSUE THREAD

**Issue by roycewilliams** [report-uri/report-uri-bugs#80]
I'm seeing a number of `font-src` blocks for `chrome-extension`, even with the "unactionable" filter enabled. The raw is as follows (HTTPS URLs removed, and line-breaks added for readability):

```
{
    "csp-report": {
        "blocked-uri": "chrome-extension",
        "document-uri": "https://www.techsolvency.com/ntp/",
        "original-policy": "default-src 'none'; 
            script-src [URLs]; 
            connect-src [URLs]; 
            img-src [URLs]; 
            style-src [URLs] 'unsafe-inline'; 
            font-src [URLs]; 
            object-src 'none'; 
            frame-src 'none'; 
            frame-ancestors 'none'; 
            base-uri [URL]; 
            form-action 'none'; 
            block-all-mixed-content; 
            report-uri https://techsolvency.report-uri.com/r/d/csp/enforce",
        "violated-directive": "font-src"
    }
}
```
In the native CSP header, I'm simply using `font-src 'self';`.

Are the chrome-extension filters applied to specific block types, or universally?

**Comment by roycewilliams** [comment]
User-Agent is "Mozilla/5.0 (Windows; Windows NT 10.0; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0".

So it appears to be a quite old version of Firefox.

**Comment by spaze** [comment]
Hey @roycewilliams, this has been deployed and filtered out since beginning of July I think but we forgot to close this one. Thanks for the report!

**Comment by roycewilliams** [comment]
Thanks, @spaze - and that matches my field experience. Thanks - closing!
