### ISSUE TITLE
500 Internal Server Error when trying to sign up for a paid account

### ISSUE THREAD

**Issue by robmoss2k** [report-uri/report-uri-bugs#83]
When attempting to sign up for a paid account, I'm sent to this URL:

https://report-uri.com/payment/billing/

The error I get is:

Server Error
We're sorry! The server encountered an internal error and was unable to complete your request. Please try again later.

error 500 | 29. 10. 2018 15:17

**Comment by ScottHelme** [comment]
Sorry about that, it should now be fixed!
