### ISSUE TITLE
Reports not visible in Dashboard

### ISSUE THREAD

**Issue by ChristophWeigert** [report-uri/report-uri-bugs#85]
Twitter Thread:
https://twitter.com/Giswald/status/1067069216484982785

Domain: https://christophweigert.com
CSP: 
content-security-policy-report-only: default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://christophweigert.report-uri.com/r/d/csp/wizard
Acount: Active **(Maybe i had a previous account with the same mail?)**
Report URI Account-Mail: Firstname . Lastname93@gmail.com
2FA: Active
Chrome Network message: wizard - POST 201

Filter settings:
![image](https://user-images.githubusercontent.com/996391/49026557-7089b580-f19e-11e8-96b1-45bc113dbca2.png)

Dashboard:
![image](https://user-images.githubusercontent.com/996391/49026593-87c8a300-f19e-11e8-81ba-0b9327080de2.png)

Chrome Network:
![image](https://user-images.githubusercontent.com/996391/49026622-9b740980-f19e-11e8-9d55-825391d83b64.png)

Setup:
* Self hosted Ghost Docker Image
* NGINX proxy
* Cloudflare DNS / Cache

**Comment by ScottHelme** [comment]
@ChristophWeigert are you still experiencing problems with this?

**Comment by ChristophWeigert** [comment]
Seems to work now.
I got some entreis for NEL reporting and the CSP wizard also shows correct entries.

Out of curiosity, what was the problem?
