### ISSUE TITLE
"no-cors" vs "follow" when using service-worker

### ISSUE THREAD

**Issue by wibimaster** [report-uri/report-uri-bugs#86]
Hi, 

I cannot receive reports when using a service-worker, it cames with this error message :

![image](https://user-images.githubusercontent.com/626666/49213443-a1e3ca80-f3c4-11e8-93d9-77df561c5e62.png)

And finally POST to report-uri is 504...

Can you explain to me why and how resolve that ?

Thanks !

**Comment by ScottHelme** [comment]
Hi @wibimaster, the POST request for the report needs to be CORS enabled. Is there any way you can change that setting?

**Comment by wibimaster** [comment]
Hum, I think it should be done on the service-worker client side, but it's automatically generated by an Angular vendor..

I have the full hand on my dedicated server, maybe I can do a proxy for that :/

**Comment by ScottHelme** [comment]
Closing unless we can be of further assistane here :)
