### ISSUE TITLE
Manifest-src directive not showing in reports

### ISSUE THREAD

**Issue by mattkirbysw** [report-uri/report-uri-bugs#87]
Looking at the graphs it looks like I have many manifest-src issues, but when I try to view reports filtered by manifest-src they don't appear.  Just filtering by day and not by directive seems to not show any manifest-src issues - even though I more of those than anything else (no image of this one).

Graph:
![image](https://user-images.githubusercontent.com/45761845/49736267-8bb9f200-fc81-11e8-8a7f-c143aa1de2db.png)

Filtering by day & directive:
![image](https://user-images.githubusercontent.com/45761845/49736116-25cd6a80-fc81-11e8-9914-2bed7ca21866.png)

Filtering by month & directive:
![image](https://user-images.githubusercontent.com/45761845/49736184-5d3c1700-fc81-11e8-9cb9-3fb1d731c544.png)
(This one warns the returned result is large, but doesn't show anything)

**Comment by ScottHelme** [comment]
I can see the problem here, currently investigating.

**Comment by ScottHelme** [comment]
I see the issue. We're not labelling the reports properly. The chances are that manifest-src is actually img-src with the wrong lavel. Working on a fix now.

**Comment by ScottHelme** [comment]
The fix for this has now been deployed, @mattkirbysw can you test and let us know if that did it please?

**Comment by mattkirbysw** [comment]
Hi - that's done it, manifest-src is now showing as img-src in the graphs - thanks for the _very_ swift response!

**Comment by ScottHelme** [comment]
No problem at all, glad to help.
