### ISSUE TITLE
DMARC Report vs Graph dates

### ISSUE THREAD

**Issue by hultqvist** [report-uri/report-uri-bugs#89]
According to the DMARC graph I have one report on the 19th but when I select the 19th on the report page there is no report.

![2019-01-22_09-40-09](https://user-images.githubusercontent.com/505330/51522702-45cc7e00-1e2a-11e9-98b8-e99717e20091.png)

On the other hand when I select the 18th (-19th) I can see the report.

![2019-01-22_09-40-40](https://user-images.githubusercontent.com/505330/51522712-48c76e80-1e2a-11e9-87dc-7058c1110dd0.png)

**Comment by ScottHelme** [comment]
Hey @hultqvist, 

The graph shows when the report was received and processed but DMARC reports usually contain data for days/weeks in the past. The Graphs page shows when we processed the report but when searching for data on the Reports page you search for the day the data was for.

**Comment by hultqvist** [comment]
I see, it's then not an "off by one" error.

The control panel presents "Report" and "Graph" next to each which made me think this was two ways to present the same data.

Your explanation would be useful on the graph page.
