### ISSUE TITLE
Global filter known Adware

### ISSUE THREAD

**Issue by owangen** [report-uri/report-uri-bugs#95]
As discussed I'm sending payloads on our top one Adware spam (cardinaldata.net).
It's caught in our img-src and script-src-elem directive.

Evidence:
https://forums.malwarebytes.com/topic/242298-blocked-website-cardinaldatanet/
https://forum.vivaldi.net/topic/34334/cardinaldata-net
https://malwarecomplaints.info/remove-cardinaldata-net/
Lots of more evidence on internet

Payload examples:
{
    "csp-report": {
        "effective-directive": "img-src",
        "blocked-uri": "https://cardinaldata.net/metric/"
    }
}
{
    "csp-report": {
        "effective-directive": "script-src-elem",
        "blocked-uri": "https://cardinaldata.net/optout/get",
        "line-number": 1,
        "column-number": 5489,
        "source-file": "https://cardinaldata.net/1fa16f6ccbee745a0c.js"
    }
}
{
    "csp-report": {
        "effective-directive": "script-src-elem",
        "blocked-uri": "https://cardinaldata.net/optout/set/lat",
        "line-number": 1,
        "column-number": 5489,
        "source-file": "https://cardinaldata.net/1fa16f6ccbee745a0c.js"
    }
}

**Comment by ScottHelme** [comment]
Thanks for the report @owangen. I've looked at our data and other sources of info online and agree this can be filtered. It will be included in our next update later today.
