### ISSUE TITLE
Invalid PHP example in setup docs

### ISSUE THREAD

**Issue by pxgamer** [report-uri/report-uri-bugs#96]
This isn't a bug with the actual service, but just the docs so I'm not sure where to add this. If this is in the wrong place, I'll close it. 👍

The PHP example on the [CSP setup page](https://docs.report-uri.com/setup/csp#getting-started) seems to be invalid.

The use of single quotes throughout means that it will try and use `none` as constant strings if you copy and paste it (throwing a warning in PHP), so it would be good to use double quotes around the header string.

```php
// Current
header('Content-Security-Policy-Report-Only: default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://{subdomain}.report-uri.com/r/d/csp/wizard')

// Updated
header("Content-Security-Policy-Report-Only: default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://{subdomain}.report-uri.com/r/d/csp/wizard");
```

**Comment by spaze** [comment]
Hey @pxgamer, nice catch, thanks for the report! I've fixed the quotes now.

**Comment by pxgamer** [comment]
Thanks @spaze, that's great. :+1:

I'll close this issue.
