### ISSUE TITLE
Format report count with commas for legibility

### ISSUE THREAD

**Issue by troyhunt** [report-uri/report-uri-bugs#97]
Just looking at my reports and when the numbers get up into the thousands, legibility suffers. I suggest we add commas to the thousands which will make it easier to read (see attached).

![2019-03-09_09-13-51](https://user-images.githubusercontent.com/273244/54061229-b3523380-424b-11e9-917d-53c2fbf5ddd0.png)

**Comment by ScottHelme** [comment]
Fix deployed.
