### ISSUE TITLE
Feature request - Support for DMARC forensic reports

### ISSUE THREAD

**Issue by ndench** [report-uri/report-uri-bugs#98]
From what I understand from the [docs](https://docs.report-uri.com/setup/dmarc/) report-uri only support the DMRAC aggregate reports. Is it possible to support the forensic reports as well? Since they contain [more detailed information](https://blog.returnpath.com/how-to-read-your-first-dmarc-reports-part-2/) they would be more useful for fixing errors.

**Comment by ScottHelme** [comment]
Hi @ndench, we don't currently have plans to support DMARC forensic reports. There are too few providers that send them, most likely for the reasons that we don't support them, so it's also difficult to test them
