### ISSUE TITLE
Switched out of report-only and now I am not getting any CSP reports

### ISSUE THREAD

**Issue by thehatsofdean** [report-uri/report-uri-bugs#99]
After updating my CSP policy in my web.config file by switching report-uri https://bcuazure.report-uri.com/r/d/csp/reportOnly; to report-uri https://bcuazure.report-uri.com/r/d/csp/enforce ; I haven't recieved any reports since I switched (I have not hit my limit - only used 3%)

Any ideas?

**Comment by ScottHelme** [comment]
I'm not aware of any service issues at present but I will take a look at your endpoint. Can you navigate to a page on your site that triggers a report and look at the request in the network tab of dev tools to see if it is being sent and gets a 201 status?

**Comment by thehatsofdean** [comment]
I can confirm it is being sent and gets a 201 status

**Comment by ScottHelme** [comment]
Hi @thehatsofdean, are you still experiencing issues here?
